// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_4M1NxdHfFOFZG5LRMWTmu1ugQlo7VTk',
    appId: '1:313246947902:android:ad38deec8fee9307cf8f6f',
    messagingSenderId: '313246947902',
    projectId: 'mynotes-ffd8',
    storageBucket: 'mynotes-ffd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYM-lU68FwA0ErVB00YljbYJ38gIInEg',
    appId: '1:313246947902:ios:6991fb3bb9d67a9acf8f6f',
    messagingSenderId: '313246947902',
    projectId: 'mynotes-ffd8',
    storageBucket: 'mynotes-ffd8.appspot.com',
    iosClientId: '313246947902-v1msur4aj80e3e98foapjg1rlbaecskq.apps.googleusercontent.com',
    iosBundleId: 'com.test.mynotes',
  );
}
